### ISSUE TITLE
Wild cards - how to use them?

### ISSUE THREAD

**Issue by Just-another-pleb** [DeanCording/node-red-contrib-fs-ops#14]
I am wanting to move a bunch of files from "a" to "b".

I think I have that worked out, but not the file name part.

I want to move all files `Reboot*`

This is what the node does when I send it the message:
```
TypeError: Cannot read property 'length' of undefined    at MoveNode._inputCallback (/home/pi/.node-red/node_modules/node-red-contrib-fs-ops/fs-ops.js:62:25)    at MoveNode.Node._emitInput (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:199:18)    at Immediate.<anonymous> (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)    at runCallback (timers.js:810:20)    at tryOnImmediate (timers.js:768:5)    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

This is what I  have for the node but it doesn't work.
(I had `*` in the destination file name.   The screen shot shows it as blank, as I was trying to get it working)

The paths are correct and set in the message.

![Screenshot from 2020-03-21 16-59-05](https://user-images.githubusercontent.com/39888280/77220548-71b1d380-6b95-11ea-9ab2-605be30115d0.png)

**Comment by rnd-debug** [comment]
Old issue, but as far as I can understand from the code, wild cards are not supported in the Move node. Also, you have to specify explicitely a destination path.
@ maintainers: does it make sense to support an empty  _destFilename_  field (in which case, the _sourceFilename _ will be reused)?
